# Pre-trained naive Bayes classifier file
training_classifier:
  class: File
  location: ../examples/hmp_data_exercise/gg-13-8-99-515-806-nb-classifier.qza
metadata_category: STSite
# Level to collapse taxonomy before performing differential abudance.  Default is 2
collapse_level: 2
# Category to give axes for PCoA plots
custom_axis: STSite
# Diversity rarefaction depth.  Default is 1080
sampling_depth: 1080
# DADA2 number of left-side bases to trim.  Default is 0
trim_left: 0
# DADA2 length to truncate sequence.  Default is 120
trunc_len: 120
